const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('studioData', {
  init: () => ipcRenderer.invoke('app:init'),
  onMenuNavigate: (callback) => ipcRenderer.on('menu:navigate', (_, page) => callback(page)),
  onPrintLead: (callback) => ipcRenderer.on('print:lead', (_, payload) => callback(payload)),
  onPrintAnalysis: (callback) => ipcRenderer.on('print:analysis', (_, payload) => callback(payload)),
  onPrintOffer: (callback) => ipcRenderer.on('print:offer', (_, payload) => callback(payload)),
  listLeads: (filters) => ipcRenderer.invoke('leads:list', filters),
  dashboard: () => ipcRenderer.invoke('leads:dashboard'),
  getLead: (id) => ipcRenderer.invoke('leads:get', id),
  saveLead: (lead) => ipcRenderer.invoke('leads:save', lead),
  deleteLead: (id) => ipcRenderer.invoke('leads:delete', id),
  duplicateLead: (id) => ipcRenderer.invoke('leads:duplicate', id),
  addActivity: (activity) => ipcRenderer.invoke('activities:add', activity),
  listTemplates: () => ipcRenderer.invoke('templates:list'),
  saveTemplate: (template) => ipcRenderer.invoke('templates:save', template),
  listOffers: () => ipcRenderer.invoke('offers:list'),
  getOffer: (id) => ipcRenderer.invoke('offers:get', id),
  saveOffer: (offer) => ipcRenderer.invoke('offers:save', offer),
  deleteOffer: (id) => ipcRenderer.invoke('offers:delete', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  getEmailSettings: () => ipcRenderer.invoke('email:getSettings'),
  saveEmailSettings: (settings) => ipcRenderer.invoke('email:saveSettings', settings),
  sendEmail: (message) => ipcRenderer.invoke('email:send', message),
  testEmailSettings: () => ipcRenderer.invoke('email:test'),
  scrapeWebsite: (url) => ipcRenderer.invoke('scraper:website', url),
  exportJson: (targetPath) => ipcRenderer.invoke('backup:exportJson', targetPath),
  importJson: (sourcePath) => ipcRenderer.invoke('backup:importJson', sourcePath),
  exportCsv: (targetPath) => ipcRenderer.invoke('backup:exportCsv', targetPath),
  importCsv: (sourcePath) => ipcRenderer.invoke('backup:importCsv', sourcePath),
  importContacts: (sourcePath) => ipcRenderer.invoke('backup:importContacts', sourcePath),
  automaticBackup: () => ipcRenderer.invoke('backup:auto'),
  openFileDialog: (options) => ipcRenderer.invoke('dialog:openFile', options),
  saveFileDialog: (options) => ipcRenderer.invoke('dialog:saveFile', options),
  openDirectoryDialog: (options) => ipcRenderer.invoke('dialog:openDirectory', options),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  copyText: (text) => ipcRenderer.invoke('clipboard:writeText', text),
  openDataFolder: () => ipcRenderer.invoke('finder:openDataFolder'),
  exportLeadPdf: (id) => ipcRenderer.invoke('pdf:lead', id),
  exportAnalysisPdf: (id) => ipcRenderer.invoke('pdf:analysis', id),
  exportOfferPdf: (id) => ipcRenderer.invoke('pdf:offer', id),
  notify: (message) => ipcRenderer.invoke('notify:test', message)
});
